CREATE TABLE CUSTOMERS (
    CUST_ID SERIAL PRIMARY KEY, 
    CUST_FIRSTNAME VARCHAR(50) NOT NULL, 
    CUST_LASTNAME VARCHAR(50) NOT NULL, 
    CUST_MIDDLENAME VARCHAR(50), 
    CUST_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    CUST_SOCIAL_PROVIDER VARCHAR(50), -- 'google' | 'facebook'
    CUST_SOCIALID VARCHAR(255) UNIQUE, -- from sign-on
    CUST_CONT_NO VARCHAR(20) NOT NULL,          -- contact number 
    CUST_CD TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- THIS IS CREATE DATE 
);