CREATE TABLE BOM (
    BOM_ID SERIAL PRIMARY KEY,
    PROD_ID INT NOT NULL,
    INV_ID INT NOT NULL,
    BOM_QUAN_REQ DECIMAL(12, 3) NOT NULL, -- QUANTITY REQUIRED 

    -- Define the Foreign Key constraints
    CONSTRAINT fk_product 
        FOREIGN KEY (PROD_ID) 
        REFERENCES PRODUCT(PROD_ID),

    CONSTRAINT fk_component 
        FOREIGN KEY (INV_ID) 
        REFERENCES INVENTORY (INV_ID),

    CONSTRAINT chk_quantity_required
    CHECK (BOM_QUAN_REQ > 0)
);