CREATE TABLE RIDER (
    RIDER_ID INT PRIMARY KEY,                   -- from delivery app 
    RIDER_NAME VARCHAR(100) NOT NULL,
    RIDER_CONTACT_NUM VARCHAR(20) NOT NULL,
    CURRENT_LOCATION VARCHAR(255) NULL);
