CREATE TABLE CART (
    ORD_ID int NOT NULL,
    PROD_ID int NOT NULL,
    CART_QUAN int DEFAULT 1,
    CONSTRAINT FK_order_id
        FOREIGN KEY (ORD_ID) 
        REFERENCES ORDERS(ORD_ID),
    CONSTRAINT FK_product_id
        FOREIGN KEY (PROD_ID) 
        REFERENCES PRODUCTS(PROD_ID),
);