CREATE TABLE FULFILLMENT (
    FULFILLMENT_ID SERIAL PRIMARY KEY,
    FULFILLMENT_TYPE VARCHAR(50) NOT NULL,
CONSTRAINT chk_FULFILLMENT_TYPE 
CHECK (FULFILLMENT_TYPE IN ('Delivery', 'Pick_Up')));

create TABLE DELIVERY (
    FULFILLMENT_ID INT NOT NULL,
    RIDER_ID INT NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CONTACT_NAME VARCHAR(100) NULL,
    CONTACT_NUMBER VARCHAR(20) NULL,
    NOTE VARCHAR(500) NULL,
    FLOOR_UNIT_NUM VARCHAR(50) NULL,
CONSTRAINT DELIVERY_PK PRIMARY KEY (FULFILLMENT_ID),
CONSTRAINT DELIVERY_FULFILLMENT_FK FOREIGN KEY (FULFILLMENT_ID) REFERENCES FULFILLMENT(FULFILLMENT_ID),
CONSTRAINT DELIVERY_RIDER_FK FOREIGN KEY (RIDER_ID) REFERENCES RIDER(RIDER_ID));

CREATE TABLE PICK_UP (
    FULFILLMENT_ID INT NOT NULL,
    PREFERRED_TIME TIMESTAMP NULL, -- Changed DATETIME to TIMESTAMP
    PICK_UP_LOCATION VARCHAR(255) NULL,
CONSTRAINT PICKUP_PK PRIMARY KEY (FULFILLMENT_ID),
CONSTRAINT PICKUP_FULFILLMENT_FK FOREIGN KEY (FULFILLMENT_ID) REFERENCES FULFILLMENT(FULFILLMENT_ID));

